[package]
name = "buildfs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
flate2 = "1.0.31"
serde = { version = "1.0.207", features = ["derive"] }
tar = "0.4.41"
tokio = { version = "1.39.2", features = [
    "rt",
    "process",
    "rt",
    "macros",
    "fs",
] }
toml = "0.8.19"
